### ISSUE TITLE
Aurora abort trace

### ISSUE THREAD

**Issue by Tinram** [charles-001/dolphie#16] opened 2023-08-18 19:02 UTC
Superb program, fulfilling such a need outside of Enterprise Monitor.  
Thank you Charles for the effort that you have put into this.

Using Dolphie from a Mac (pip-derived version), everything connects and works well with MySQL 8.0 instances.  However, when connecting to Aurora 2 instances from the same Mac, Dolphie aborts.  I attach one such trace output.

[dolphie_pip_trace_aurora2.txt](https://github.com/charles-001/dolphie/files/12383338/dolphie_pip_trace_aurora2.txt)

**Comment by charles-001** [comment] 2023-08-18 20:18
Hi @Tinram - thanks for the bug report! I see what the issue is... I guess this is what happens when I don't test for RDS hah... mostly because I no longer have access to AWS.  I've pushed a fix for it to the code base. Any chance you can do this:
1. `git clone`
2. `curl -sSL https://install.python-poetry.org | python3 -` (if you don't have it already installed)
3. `poetry install`
4. `poetry run dolphie`

This will test the change so I know if all is well before pushing a new version.

**Comment by Tinram** [comment] 2023-08-18 20:43
@charles-001 
Yes, have completed the above steps.
Dolphie now connects successfully to Aurora 2 and displays output.

Thank you!

**Comment by charles-001** [comment] 2023-08-18 20:50
Awesome - this will be released in 3.0.3 later today. Thanks again for your bug report!

**Closed** 2023-08-18 20:51 UTC
